swagger: "2.0"

info:
  title: "Model Developer Service"
  version: "1.0"

basePath: /v1

paths:
  /ModelDeveloperService/prediction:
    post:
      consumes: [application/json]
      produces: [application/json]
      summary: Gets prediction for given matchup
      operationId: api.call_model_developer_service.class_instance.get_prediction
      parameters:
        - in: body
          name: PredictionRequest
          required: true
          schema:
            type: object
            items:
              $ref: '#/definitions/PredictionRequest'
      responses:
        '200':
          description: 'Data containing prediction for given match-up'
          schema:
            type: object
            items:
              $ref: '#/definitions/PredictionResponse'

definitions:
  PredictionRequest:
    type: object
    properties:
      league_info:
        type: object
        $ref: '#/definitions/LeagueInfo'
  LeagueInfo:
    type: object
    properties:
      country:
        type: string
      home_team:
        type: string
      away_team:
        type: string
  PredictionResponse:
    type: object
    properties:
      forecast:
        type: object
        $ref: '#/definitions/Forecast'
      score:
        type: object
        $ref: '#/definitions/Score'
  Forecast:
    type: object
    properties:
      home_win:
        type: number
      away_win:
        type: number
      tie:
        type: number
  Score:
    type: object
    properties:
      home:
        type: number
      away:
        type: number
      predicted_home:
        type: number
      predicted_away:
        type: number
